import './styles/globalstyle.scss'
import './styles/page.scss'
import './scripts/card-dnd.ts'
import './scripts/init.ts'
import './scripts/column.ts'
import './scripts/card.ts'
import './scripts/activity.ts'
